visualizer:
  ros__parameters:
    x_range: [0.0, 4.0]
    y_range: [0.0, 6.0]
    resolution: [480, 320]
    stiffness_range: [200, 1500]
    uncertainty_threshold: 1.0
    uncertainty_alpha: 100

# mocapCollection:
#   ros__parameters:
#     localIP: 


leg_measurements_publisher:
  ros__parameters:


top_view_camera:
  ros__parameters:

data_collector:
  ros__parameters:
    csv_file: whitesandtest

mapping_node:
  ros__parameters:
    x_range: [0.0, 4.0]
    y_range: [0.0, 6.0]
    resolution: [480, 320]
    noise_level: 0.1
    length_scale: 0.5
    sigma_f: 1.0


fake_path_publisher:
  ros__parameters:
    start_position: [0.0, 0.0, 0.0]  # [x, y, z]
    goal_position: [5.0, 5.0, 0.0]   # [x, y, z]
    num_points: 50
    publish_rate: 1.0
    