visualizer:
  ros__parameters:
    x_range: [-8.0, 8.0]
    y_range: [-10.0, 10.0]
    resolution: [1000, 800]
    stiffness_range: [500, 1400]
    uncertainty_threshold: 1.0
    uncertainty_alpha: 200

# mocapCollection:
#   ros__parameters:
#     localIP: 


leg_measurements_publisher:
  ros__parameters:


top_view_camera:
  ros__parameters:

data_collector:
  ros__parameters:
    csv_file: rsstest25

mapping_node:
  ros__parameters:
    x_range: [-8.0, 8.0]
    y_range: [-10.0, 10.0]
    resolution: [1000, 800]
    noise_level: 0.1
    length_scale: 20.0
    sigma_f: 1.0
